language: python
virtualenv:
  system_site_packages: true
python:
  - "3.6"
  - "3.6.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest -c pytest.ini
