[tool.poetry]
name = "syncshell"
version = "1.0.3"
description = "Keep your machine's shell history synchronize."

license = "MIT"

authors = [
    "Masoud Ghorbani <msud.ghorbani@gmail.com>"
]

readme = "README.md"

repository = "https://github.com/msudgh/syncshell"
homepage = "https://github.com/msudgh/syncshell"

keywords = ["sync", "shell", "history", "bash", "zsh"]

[tool.poetry.dependencies]
python = "3.7"
black = "22.3.0"
fire = "0.1.3"
flake8 = "4.0.1"
halo = "0.0.12"
PyGithub = "1.55"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"
pytest-testdox = "^3.0.1"
